version: '3'
services:
  mysql-db:
    image: mysql:5.7
    restart: always
    ports:
      - '3306:3306'
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    environment:
      MYSQL_ROOT_PASSWORD: prisma
    volumes:
      - mysql:/var/lib/mysql
volumes:
  mysql: ~

